

# [endpoint=https://ld.bs.ch/query]
PREFIX adhoc: <http://adhoc>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX premis: <http://www.loc.gov/premis/rdf/v3/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX relSubType: <http://id.loc.gov/vocabulary/preservation/relationshipSubType/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX schema: <http://schema.org/>
PREFIX stabs-ext: <https://ld.bs.ch/RiC/vocabularies/extentTypes/>
PREFIX stabs-rico: <https://ld.bs.ch/ontologies/StABS-RiC/>
PREFIX stabs-rst: <https://ld.bs.ch/RiC/vocabularies/recordSetTypes/>
PREFIX void: <http://rdfs.org/ns/void#>

CONSTRUCT {?record ?allrecordprops ?allrecordobj ;
            adhoc:expressedDate ?expr_date ;
            rico:isAssociatedWithRule ?rule ;
            rico:hasOrHadDigitalInstantiation ?free_inst
            .
           ?free_inst ?allinprops ?allinvals ;
                      adhoc:download ?location
           .
           ?file ?allfiprops ?allfivals .
           ?rule ?ruleprops ?rulevals .
           ?ruletype ?allruleprops ?allrulevals .
           ?rst ?allrstprops ?allrstvals
}  


WHERE { GRAPH <https://ld.bs.ch/graph/ais-metadata> 
    {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            ?allrecordprops ?allrecordobj ;
            rico:isAssociatedWithDate/rico:expressedDate ?expr_date ;
            rico:isAssociatedWithRule ?rule ;
            rico:hasRecordSetType ?rst ;
            ^rico:isOrWasDigitalInstantiationOf ?free_inst ;
            .
    ?free_inst ?allinprops ?allinvals ;
               relSubType:hsp ?file ;
               relSubType:hsp/premis:storedAt/rdf:value ?location
    .
    ?file ?allfiprops ?allfivals
    .
    ?rule ?ruleprops ?rulevals ;
          rico:hasOrHadRuleType ?ruletype
    .
    ?ruletype ?allruleprops ?allrulevals
    .
    ?rst ?allrstprops ?allrstvals
    .
    }
}