

# [endpoint=https://ld.bs.ch/query]
PREFIX adhoc: <http://adhoc>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX premis: <http://www.loc.gov/premis/rdf/v3/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX relSubType: <http://id.loc.gov/vocabulary/preservation/relationshipSubType/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX stabs-ext: <https://ld.bs.ch/RiC/vocabularies/extentTypes/>
PREFIX stabs-rico: <https://ld.bs.ch/ontologies/StABS-RiC/>
PREFIX stabs-rst: <https://ld.bs.ch/RiC/vocabularies/recordSetTypes/>
PREFIX void: <http://rdfs.org/ns/void#>

CONSTRUCT {
  ?s ?p ?o .
}
WHERE {

  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" .
    ?record ?p ?o .
    BIND(?record AS ?s)
  }

  UNION
  
  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            rico:isAssociatedWithDate ?date .
    
    ?date ?p ?o .
    BIND(?date AS ?s)
  }
      
  UNION

  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            ^rico:isOrWasDigitalInstantiationOf ?free_inst .

    ?free_inst ?p ?o .
    BIND(?free_inst AS ?s)
  }

  UNION

  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            ^rico:isOrWasDigitalInstantiationOf ?free_inst .

    ?free_inst relSubType:hsp ?file .

    ?file ?p ?o .
    BIND(?file AS ?s)
  }
  
  UNION
  
  {
     ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
             rico:isAssociatedWithRule ?rule .
    ?rule ?p ?o .
    BIND(?rule AS ?s)
  }
  UNION
  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            rico:isAssociatedWithRule/rico:hasOrHadRuleType ?ruletype .
    ?ruletype ?p ?o .
    BIND(?ruletype AS ?s)
  }
  UNION
  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            rico:hasRecordSetType ?rst .
    ?rst ?p ?o .
    BIND(?rst AS ?s)
  }
    UNION
  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            rico:hasRecordSetType/rdfs:subClassOf ?ricrst .
    ?ricrst ?p ?o .
    BIND(?ricrst AS ?s)
  }
  UNION
  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            rico:hasRecordSetType/skos:topConceptOf ?conc .
    ?conc ?p ?o .
    BIND(?conc AS ?s)
  }
  UNION
  {
    ?record rico:identifier "PÖA-REG 17a 4-2 (1) 4" ;
            rico:hasRecordSetType/rdfs:subClassOf/skos:inScheme ?scheme .
    ?scheme ?p ?o .
    BIND(?scheme AS ?s)
  }
}