


# [endpoint=https://ld.bs.ch/query]
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX stabs-acr: <https://ld.bs.ch/RiC/vocabularies/acRules/>

SELECT ?r ?title ?signatur ?viewer ?iiif
WHERE {
  GRAPH <https://ld.bs.ch/graph/ais-metadata> 
  {
    {?i a rico:Instantiation ;
        rico:isOrWasDigitalInstantiationOf ?r .
    }
    ?r rico:isAssociatedWithRule stabs-acr:free-online ;
       rico:title ?title ;
       rico:type ?archivalienart ;
       rico:identifier ?signatur
       .
    filter(regex(?title, 'Petersgraben'))
    filter(regex(?archivalienart, 'Bild'))
    ?i rdfs:seeAlso ?viewer ;
       schema:url ?iiif
       .
  }
}
LIMIT 100